apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        track: stable
    spec:
      containers:
        - name: hello
          image: "smolsky/ud615_dotnetcore_hello:1.0.0"
          ports:
            - name: http
              containerPort: 80 
          resources:
            limits:
              cpu: 0.2
              memory: "100Mi"
